Panels:
  - Name:   Project Settings
    IsOpen: false
  - Name:   Preferences
    IsOpen: false
  - Name:   Game
    IsOpen: true
  - Name:   Scene
    IsOpen: true
  - Name:   Console
    IsOpen: true
  - Name:   Scene Hierarchy
    IsOpen: true
  - Name:   Shader Library
    IsOpen: true
  - Name:   Content Browser
    IsOpen: true
  - Name:   Inspector
    IsOpen: true
  - Name:   Asset Registry
    IsOpen: false
  - Name:   Script Engine
    IsOpen: false
  - Name:   Statistics
    IsOpen: true